dist: trusty
sudo: false
language: java
jdk:
- openjdk8
install: true
before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx1G"
 - vmstat -s
script: mvn -e -B verify
cache:
  directories:
  - $HOME/.m2
